### ISSUE TITLE
tab autocomplete bug

### ISSUE THREAD

**Issue by Tsai1005** [zakaziko99/agnosterzak-ohmyzsh-theme#10]
I change the themes from agnoster to agnosterzak,then I found that the "Tab"(auto complete function) sometimes will no align the position it should be,

**Comment by WALL-EEEEEEE** [comment]
I encountered the some problems either.

**Comment by ozamorowski** [comment]
Same here. 
Screenshot after hitting TAB:
![selection_003](https://cloud.githubusercontent.com/assets/1939688/18026131/03193d5a-6c3e-11e6-9fb2-b72c4d8d05eb.png)

**Comment by afrozalm** [comment]
I'm facing the same problem.

@zakaziko99  This bug is due to the use of _$fg_bold_ and _$fg_no_bold_ 

Can be sloved by replacing all _$fg_bold[color]_ terms with _%{$fg_bold[color]%}_

**Comment by Curzy** [comment]
thx for @afrozalm 
Resolved with replacing like you've commented 

**vim replace command**
':%s/$fg_bold[([a-z]+)]/%{$fg_bold[\1]%}/g'
':%s/$fg_no_bold[([a-z]+)]/%{$fg_no_bold[\1]%}/g'

**Comment by ShakataGaNai** [comment]
Thank you much @afrozalm . Works great!

**Comment by Tsai1005** [comment]
Thx @afrozalm ,it works!
