### ISSUE TITLE
Battery percentage isn't visible

### ISSUE THREAD

**Issue by saisrivathsa** [zakaziko99/agnosterzak-ohmyzsh-theme#12]
Battery percentage isn't showing up instead I see a setting shaped icon. I use linux mint (gnome-terminal)

**Comment by kevincaradant** [comment]
Hi

If you write this command in the terminal: `echo "$(acpi | cut -f2 -d ',' | tr -cd '[:digit:]')"`

What's the result ? In my case acpi wasn't installed. Maybe it's your case.

**Comment by saisrivathsa** [comment]
Oh, thanks !! acpi wasn't installed in my PC. It's working now :D

**Comment by kevincaradant** [comment]
You're welcome.  I didn't see myself  before but there is also an issue on it just here ^^:https://github.com/zakaziko99/agnosterzak-ohmyzsh-theme/issues/8

It's seems he suggested the same answer :). But I'm happy to have fixed your problem

**Comment by catliaw** [comment]
The battery percentage indicated in iTerm2 is not the same as indicated in top-right of my laptop screen.

How do you install acpi? I am using iTerm2 (running zsh) on Mac OS X. I tried to 'brew install acpi' and 'npm install acpi' and neither work. I also tried 'yum install acpi'.

**Comment by mqliutie** [comment]
@saisrivathsa  How can install it on Mac ?
