### ISSUE TITLE
Weird display

### ISSUE THREAD

**Issue by seajean** [zakaziko99/agnosterzak-ohmyzsh-theme#3]
The colors is not the same as your screenshot.
![qq20160314-0](https://cloud.githubusercontent.com/assets/1409603/13734468/454bc1a8-e9d9-11e5-86d4-2811a20c3caf.png)

**Comment by crazylinuxsir** [comment]
use iTerm with zsh  and choose a dark theme

**Comment by seajean** [comment]
OK，I will try. Thanks!
