### ISSUE TITLE
Cursor is shifted when searching in history

### ISSUE THREAD

**Issue by maximede** [zakaziko99/agnosterzak-ohmyzsh-theme#5]
Hello ,

I have a minor issue with the theme on MacOSX with Iterm.
When I search in the history (<kbd>ctrl</kbd>+<kbd>r</kbd>), the cursor get displaced : 

![screen shot 2016-03-29 at 11 09 52 am](https://cloud.githubusercontent.com/assets/2980192/14118584/fe15bc9a-f59e-11e5-839b-6a17991610a6.png)

Any idea why ? 

Thanks, 

Maxime

**Comment by NiharG15** [comment]
This issue is also present on Arch Linux with Gnome-Terminal. If I change the theme to anything else, its resolved. So I think its definitely this theme. 
![agnosterzakbug](https://cloud.githubusercontent.com/assets/2757665/14142740/06668aee-f6a5-11e5-99ed-3fffc4059a33.png)

**Comment by zakaziko99** [comment]
this issue is due for breaking the info output to two separate lines, i'm on for fixing that

@maximede, @NiharG15 Thanks you for reporting that

**Comment by NiharG15** [comment]
Any updates @zakaziko99 ?

**Comment by ozamorowski** [comment]
#10 is probably same issue.

**Comment by miked0004** [comment]
It's not just the newline as I've found by removing it

**Comment by nomike** [comment]
On several occurrences (around those " $fg_bold[magenta]%(!.%{%F{magenta}%}.)" parts) the "%{%}" escapes were missing. I added them, now the issue's are completely gone. I created a pull request for this as you can see above.

**Comment by nomike** [comment]
Just saw that someone already mentioned this in #10. Well, now there is a pull request for this.
