### ISSUE TITLE
Default color scheme & font

### ISSUE THREAD

**Issue by bre7** [zakaziko99/agnosterzak-ohmyzsh-theme#7]
Hi zakaziko,

Would you mind sharing your color scheme and font name ? The one shown on the screenshots looks nice but haven't been able to find it (tested almost all the fonts listed).

Is it the stock Solarized Dark with Menlo+Powerline ? Colors seem off.

**Comment by zakaziko99** [comment]
Hi @bre7,

I'm using the 'DejaVuSansMono' powerline font (the one on the screenshot), you can also use 'Meslo' for MacOS or LinuxOS. You can find both on this link [https://github.com/powerline/fonts](https://github.com/powerline/fonts).

For the color scheme, you can find it [here](https://github.com/zakaziko99/zaka-files/blob/master/misc-files/terminal-color-scheme)

**Comment by bre7** [comment]
Thanks :) In case anyone wants the theme, export it to any format from here: https://terminal.sexy/#ACs209naDGJ43DIvMbI12qQAJovS0zaCALa27ujVAHN5y0sWhZkAemENAGulih1SH3lx_fbj
